### ISSUE TITLE
Problem when deserialize Request body - Testing

### ISSUE THREAD

**Issue by ntk148v** [cloudcomputinghust/CAL#19]
I am facing some JSON decoder problems. When write unittest for `wsgi.py`, it raise this exception 'ValueError: No JSON object could be decoded'. Go deep in there, i use `simple,json` module for better error msg, then i get bellow msg:

```
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
In most cases json.loads or simplejson.loads - JSONDecodeError: Expecting value: line 1 column 1 (char 0) error is due to :

```
non-JSON conforming quoting
XML/HTML output (that is, a string starting with <), or
incompatible character encoding
```

Ultimately the error tells that at the very first position the string already doesn't conform to JSON. I recheck this, but still dont know reason and solution:

```python
self.body = '{"cloud":"cloud1"}'
```
I try to print body before json.loads(), it return exactly {"cloud": "cloud1"} and when run json.loads('{"cloud":"cloud1"}'), it works like a charm. But, if json.loads(body) it doesnt work.

P/s: falcon.Request doesnt have `body` attribute. It make me confused at the first time, but now i understand why:

```
It’s called stream instead of body to emphasize the fact that you are really reading from an input stream; Falcon never spools or decodes request data, instead giving you direct access to the incoming binary stream provided by the WSGI server.
```
P/s2: I just push to my individual repo, for test any solution without affect original CAL repo. Check test_wsgi [here](https://github.com/ntk148v/CAL/blob/master/cal/tests/unit/test_wsgi.py#L83)

**Comment by hieulq** [comment]
@ntk148v will take a look and give feedback later.

**Comment by hieulq** [comment]
1. Your code base is not compatible with python 3, please use json.loads(datastring.decode()..) instead of json.loads(datastring,..)
2. Your TestMiddleWare never call your two hooks, so this will always lead to JsonMalform error.

**Comment by ntk148v** [comment]
@hieulq 
1. I try decode request body before put it in json.loads() method. It still get error, so i remove it.
2. I pretty sure this is not the reason. Because `process_request` middleware raise an error(ValueError with JSON), falcon will skip any lower layers/middlewares, in this case is `process_resource`. So, 2 hooks never called.

I still think problem is body of request. It lead to ValueError, like i said.

**Comment by hieulq** [comment]
@ntk148v IMO, falcon itself will call to the stack of middleware function (process_request) before processing resources (with hooks), the problem here is in this stack context, there is only one request object, or you can call a stream, right?
So, in your test case, there are 2 middleware based on 2 hooks. When you simulate request in falcon, the request will be sent to the 1st middleware (_first_hook), grab the stream body. Then next to the 2nd middleware with the empty body (because the 1st middleware have eaten whole of stream body), so the body is always empty and make falcon raise ValueError.

References is falcon flow with middle, ref: http://falcon.readthedocs.io/en/stable/api/middleware.html?highlight=middleware

`mob1.process_request
    mob2.process_request
        mob3.process_request
            mob1.process_resource
                mob2.process_resource
                    mob3.process_resource
            <route to responder method>
        mob3.process_response
    mob2.process_response
mob1.process_response`

I think we are using middleware with hooks in falcon in wrong way. Because the old wsgi code is custom wsgi, but falcon use middleware in very different way.

**Comment by ntk148v** [comment]
@hieulq it may be right, i will recheck this then tell u soon.

**Comment by hieulq** [comment]
@ntk148v take a look at this example:
http://falcon.readthedocs.io/en/stable/user/quickstart.html#more-features

You can see they create 3 different middlewares.

**Comment by hieulq** [comment]
@ntk148v I prefer you rewrite the test_wsgi structure for handling right behaviors of falcon. The 2 hooks need to be put in validator context of request.

Another problem here is currently we are missing test case for process resources, right?

**Comment by ntk148v** [comment]
@hieulq i read this tut, but i think using 1 middleware still works. (and reality, it doesn't, too bad). I will rewrite it.

**Comment by hieulq** [comment]
@ntk148v +2, do we need to delete the unittest branch?

**Comment by hieulq** [comment]
@ntk148v ack, too fast too furious
Thanks for your effort. Keep moving forward for all tasks of this week.
