### ISSUE TITLE
Deploy OpenStack de-facto API and OpenStack AWS API for CAL testing purpose

### ISSUE THREAD

**Issue by hieulq** [cloudcomputinghust/CAL#20]
@nhatbkk57 Please finish deploying 2 OpenStack instance, 1 for defacto OpenStack API and 1 for AWS API. We need to finish this task in this week and begin testing after @daikk115 works in resource branch.

@daikk115 Please keep up with another progresses. You are moving a bit slower than another guys in our team. So, try your best and rule them all, dude.

**Comment by hieulq** [comment]
@nhatbkk57 ping?

**Comment by nhatbkk57** [comment]
@hieulq when deploying OPS instance, i've got some issues. The network topology is: 
- OPS_ExtNet: 10.0.1.0/24 as physical provider network and have a interface attach to Internet Router (link between OPS_ExtNet and real External Network)
- OPS_IntNet: 100.0.1.0/24 as physical selfservice network
- Instance have 2 interface attach to 2 port of OPS_ExtNet and OPS_IntNet
- Neutron 's configuration is with selfservice network 
The installation seems no errors but when i try to create a Network, i disconnect to the instance. I still don't know why? May I try to re-install with config with provider network only!

**Comment by hieulq** [comment]
@nhatbkk57 write down all issues related to Mitaka OPS and EC2-API.

**Comment by hieulq** [comment]
@nhatbkk57 ping, what issues did you meet?

**Comment by nhatbkk57** [comment]
@hieulq the main issue still is configuration for neutron network. With using OVS configuration, both installation follow manual guide or using devstack, when I modify network interface (eth0, br-ex) and add eth0 to br-ex, network of VM always gets error and I can't ping or ssh after.

I've installed OPS by manual or using devstack before on my local VM launched by KVM but I've not got this error yet. Should I test EC2-API on my local VM instead of Cloud VM until fixing that error???

**Comment by hieulq** [comment]
@nhatbkk57 go ahead and test in isolated environment without OpenStack. You should try to test in one KVM VM or Virtualbox VM.

**Comment by hieulq** [comment]
@nhatbkk57 update all info related to aws and openstack testbed (IP, endpoint, username, password..) and usage to doc folder in master branch

**Comment by hieulq** [comment]
@nhatbkk57 ping?

**Comment by nhatbkk57** [comment]
https://github.com/cloudcomputinghust/CAL/blob/master/docs/tested-OPS-usage-guide.md
